<a href="https://colab.research.google.com/github/AhsenRiaz/Numpy-And-Pandas/blob/main/01_numpy_in_depth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# creating 1D numpy array
a_np = np.array([1,2,3,4])
print(a_np)
a_np.shape

[1 2 3 4]


(4,)

In [5]:
B_np = np.array([[1,2,3], [4,5,6]])
print(B_np)
B_np.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

Initial Placeholders

In [9]:
c_np = np.zeros((4,5), dtype=float)
c_np

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
d_np = np.ones((3,4));
d_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
e_np = np.full((4,5), 7);
e_np

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
# create identity matrix - 3x3
identity_np = np.eye((6))
identity_np

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
# a numpy array of random values
random_np = np.random.random((4,5))
print(random_np)

[[0.98839424 0.62266063 0.53815066 0.7249151  0.83213993]
 [0.42310847 0.50443688 0.75151819 0.96927375 0.69897487]
 [0.3656327  0.90927466 0.38112987 0.70575898 0.2330206 ]
 [0.1028046  0.05271704 0.44558579 0.10707447 0.56231061]]


In [19]:
# a numpy array of random integers
randint_np = np.random.randint(1,5, (5,5));
randint_np

array([[1, 3, 3, 4, 3],
       [4, 4, 2, 3, 2],
       [3, 4, 1, 1, 2],
       [4, 3, 4, 2, 4],
       [3, 2, 4, 2, 2]])

In [20]:
a_linsp_np = np.linspace(10,30,6) # break 10 and 30 intro 6 elements
a_linsp_np

array([10., 14., 18., 22., 26., 30.])

In [26]:
b_arng_np = np.arange(10,30,5) # break and jump each element by 5 units exlusive of the last
b_arng_np

array([10, 15, 20, 25])

In [31]:
# convert a list to numpy array
a_list = [10,20,30,40,50];
a_list_to_np = np.asarray(a_list)
print(a_list_to_np)
type(a_list_to_np)

[10 20 30 40 50]


numpy.ndarray

Analysing Numpy array

In [35]:
# a numpy array of random integers
randint_np = np.random.randint(1,5, (5,5));
print(randint_np)
print(randint_np.shape)
print(randint_np.ndim)
print(randint_np.size)
print(randint_np.dtype)


[[3 1 2 1 4]
 [3 1 4 3 2]
 [3 2 3 1 4]
 [2 2 2 2 1]
 [3 1 4 2 3]]
(5, 5)
2
25
int64


Mathematical Operations

In [36]:
a_np = np.random.randint(1,10, (3,3))
a_np

array([[8, 5, 2],
       [7, 1, 3],
       [3, 4, 1]])

In [37]:
b_np = np.random.randint(10,20, [3,3])
b_np

array([[12, 18, 13],
       [19, 18, 19],
       [19, 15, 19]])

In [38]:
c_np = np.add(a_np, b_np)
c_np

array([[20, 23, 15],
       [26, 19, 22],
       [22, 19, 20]])

In [39]:
d_np = np.transpose(a_np);
d_np

array([[8, 7, 3],
       [5, 1, 4],
       [2, 3, 1]])

Numpy Array Reshaping

In [48]:
a_np = np.random.randint(1,10, (2,3))
print(a_np)
print(a_np.shape)

[[2 1 2]
 [3 1 6]]
(2, 3)


In [50]:
b_np = a_np.reshape(3,2);
print(b_np)
print(b_np.shape)

[[2 1]
 [2 3]
 [1 6]]
(3, 2)
