<a href="https://colab.research.google.com/github/AhsenRiaz/Numpy-And_Pandas/blob/main/03_pandas_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A dataframe can be described as multiple different series combined with one another

In [22]:
import numpy as np
import pandas as pd
cars_csv = 'https://raw.githubusercontent.com/AhsenRiaz/Numpy-And_Pandas/main/cars.csv'

In [ ]:
sales_np = np.random.randint(1000, 5000, (4,3))
print(sales_np, "\n")

names = ["Tom", "John", "Bob", "Jerry"]
print(names, "\n")

months = ["April", "May", "June"]
print(months, "\n")

sales_df = pd.DataFrame(sales_np, index=names, columns=months)
print(sales_df);

[[3860 4608 4621]
 [2925 3794 4390]
 [3938 1450 2705]
 [2764 4175 1244]] 

['Tom', 'John', 'Bob', 'Jerry'] 

['April', 'May', 'June'] 

       April   May  June
Tom     3860  4608  4621
John    2925  3794  4390
Bob     3938  1450  2705
Jerry   2764  4175  1244


# Importing DataFrame

In [32]:
cars_csv='https://raw.githubusercontent.com/AhsenRiaz/Numpy-And_Pandas/main/cars.csv'

df = pd.read_csv(cars_csv)
df.head() # will show only the first 5 rows of the data set

car       type  year  price finance   day  dealer  \
0  Mercedes-Benz A-Class      sedan  2019  39000      no   Sun    Mike   
1                Audi A6      sedan  2021  67800     yes   Mon     Sam   
2          Nissan Altima      sedan  2015  17500      no   Sun    Mike   
3      Chevrolet Equinox        SUV  2013   9600      no   Wed  Turner   
4         Hyundai Accent  hatchback  2017  23000     yes  Thur   Maddy   

   customer  social_security sex  
0   Stanley        555342396   M  
1  Brittany        887766234   F  
2      Todd        998573477   M  
3    Jasime        342234563   F  
4       Sam        570566354   M